### PR TITLE
List component

### PR DESCRIPTION
**Pull request by 3lvis**
Reworked the table component and made it a list component, this simplifies the complexity of the view hierarchy as well as allowing for a simpler component model.

### Before

```swift
let elements = [
    TextTableElement(title: "FINN-kode", detail: "123456789"),
    DateTableElement(title: "Sist endret", date: Date()),
]
let table = [TableComponent(components: elements)]
```

### After

```swift
let textList = TextListComponent(title: "FINN-kode", detail: "123456789")
let separator = SeparatorComponent()]
let dateList = DateListComponent(title: "Sist endret", date: Date())
```

list

### CODE REVIEW

**Comment by ulrikus** [comment]
I just think it looks a bit weird with the spacing between the separator now, but it's a good idea.

**Comment by 3lvis** [comment]
@ulrikus does that mean this is approved?

**Comment by ulrikus** [comment]
If this is the way it's going to look I guess I can approve it, but if not I think something should be done to fix it.

**Comment by 3lvis** [comment]
I think it can stay that way for now, right now there's too little spacing.

**Comment by ulrikus** [comment]
Ok, although that would be a really quick fix the way it used to be.

**Review by ulrikus — APPROVED** [review]
I guess I don't 100% agree, but if this is better let do it!

**Comment by 3lvis** [comment]
Something happened while rebasing, I'll just move the files to a fresh branch.

**Pull request closed without merging**
