### PR TITLE
Restructuring

### PR DESCRIPTION
**Pull request by ulrikus**
# What?
Refactors the `PhoneNumberComponentView` and the `MessageButtonComponentView` and make separate delegate methods for the different actions in the component view. 

# Why?
The components are more generic and suited for actual use. Though, there are still some things that will need figuring out, like initialization, i.e the phone number has been given from the start which is not the case in the app.

### CODE REVIEW

**Comment by ulrikus** [comment]
@3lvis Check it out now. I think I'm done with this. Now I should just (almost) repeat this structure for the other components. Would be nice to have this merged first though.

**Comment by ulrikus** [comment]
What should I do to get this du pass the tests on CircleCI @3lvis ?

**Comment by 3lvis** [comment]
@ulrikus The project is not building, I guess that's why it's failing.

**Comment by 3lvis** [comment]
>❌  /Users/distiller/components-ios/Detail/ObjectView.swift:15:79: use of undeclared type 'MessageButtonComponent'

**Comment by ulrikus** [comment]
It builds here, but I see there are some changes on master I have to pull first. Didn't get them until now. Maybe they are the reason.

**Comment by ulrikus** [comment]
Ohh.. I had to add the `MessageButtonComponent` to the project (or remove the place I called it, but i didn't want to do that :) ). Anyways, it passes now.

**Review by 3lvis — APPROVED** [review]

**Pull request merged**
