### PR TITLE
Object page recreation

### PR DESCRIPTION
**Pull request by ulrikus**
# What?
The object page recreated from the "hardcoded" view components made earlier by using the matrix data model for the components.

### TODO:
- [ ] Make flat buttons aligned to leading edge
- [ ] Inject data for images/text etc.

more?

# Why?
To demonstrate the concept

### CODE REVIEW

**Comment by 3lvis** [comment]
😱

**Comment by ulrikus** [comment]
Does that mean 👍 or 👎  @3lvis  :)

**Comment by 3lvis** [comment]
I meant 😱 👏

**Comment by 3lvis** [comment]
I guess this isn't done yet? I can see the WIP badge :)

**Comment by ulrikus** [comment]
Yes, there are a few things that should be checked out, I'm just not sure how important they are for the sake of proving the concept in this case. What do you think?

**Review by 3lvis — APPROVED** [review]
We can continue as it is :)

**Comment by ulrikus** [comment]
So just merge?

**Comment by 3lvis** [comment]
Do it 🔥!

**Pull request merged**
