### PR TITLE
Collapsable description component

### PR DESCRIPTION
**Pull request by ulrikus**
# What?
Makes a collapsable/expandable UITextView with animations that hides the expand button if the text is too short. There is a toggle switch called `isHidingCollapseButton` which decides if the collapse button should hide when the expand button is tapped. The gradient view hints to that the description is longer and uses an observer to detect orientation change so that it can update its frame.

_NB. The text stored in `ObjectViewController` is now **VERY** long, and too long for the simulator. That text might need to be shortened, but it's not important._

### CODE REVIEW

**Comment by 3lvis** [comment]
>May need to support attributed text

Attributed text is not optional, we have to have it.

**Comment by ulrikus** [comment]
How about now @3lvis?

**Comment by 3lvis** [comment]
Perfect 👌

**Review by 3lvis — APPROVED** [review]
I’ll do more testing later today, I don’t have my computer with me at the moment :)

**Comment by ulrikus** [comment]
Sure. Should I still S&M (Squash & Merge)?

**Comment by 3lvis** [comment]
#yolo

**Comment by 3lvis** [comment]
Gave it a try and the animation is super smooth 👏

**Comment by 3lvis** [comment]
The only feedback is that I think we should consider having different delegates for the different components, in case you only want to implement one component you should have to conform to all the methods in the delegate. We could have: "linkDelegate", "collapsableDescriptionDelegate" etc.

**Pull request merged**
